apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alloy
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
      - namespaces
      - nodes
    verbs:
      - get
      - list
      - watch
